name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install Chrome and ChromeDriver using apt
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver

      # Step 5: Add ChromeDriver to PATH
      - name: Add ChromeDriver to PATH
        run: |
          export PATH=$PATH:/usr/lib/chromium-browser/

      # Step 6: Install Maven dependencies
      - name: Install dependencies
        run: mvn install

      # Step 7: Run Selenium tests
      - name: Run tests
        run: mvn test
