name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      # Step 3: Install Microsoft Edge
      - name: Install Microsoft Edge
        run: |
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-stable

      # Step 4: Install Edge WebDriver
      - name: Install Edge WebDriver
        run: |
          EDGE_VERSION=$(microsoft-edge --version | grep -oP '\d+\.\d+\.\d+')
          wget https://msedgedriver.azureedge.net/$EDGE_VERSION/edgedriver_linux64.zip
          unzip edgedriver_linux64.zip
          sudo mv msedgedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/msedgedriver











      # Step 6: Install Maven dependencies
      - name: Install dependencies
        run: mvn install

      # Step 7: Run Selenium tests
      - name: Run tests
        run: mvn test
